=== javierbarbe/ordenadornegro/XML/practica xml dtd xmlschema/practica.dtd
<!ELEMENT pedidos (pedido)>
<!ELEMENT pedido  (trabajador,fecha,observaciones?,articulo)>
    <!ATTLIST pedido codigo CDATA #REQUIRED >
    <!ATTLIST pedido  observaciones (urgente|incompleto) #IMPLIED>
    <!ATTLIST pedido plazo_revision CDATA #REQUIRED>
    <!ELEMENT trabajador EMPTY>
       <!ATTLIST trabajador nombre CDATA #REQUIRED>
    <!ELEMENT fecha EMPTY> 
        <!ATTLIST fecha dia CDATA  #REQUIRED>
        <!ATTLIST fecha mes CDATA  #REQUIRED>
        <!ATTLIST fecha anio CDATA  #REQUIRED>
    <!ELEMENT observaciones (#PCDATA)>
        
    <!ELEMENT articulo (n_unidades,precio,observaciones)>
        <!ELEMENT n_unidades (#PCDATA)>
        <!ELEMENT precio (#PCDATA)>
        <!ATTLIST articulo cod_articulo CDATA  #REQUIRED>

=== javierbarbe/ordenadornegro/XML/practica xml dtd xmlschema/practicadtd.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>


<!DOCTYPE pedidos SYSTEM "./practica.dtd">
<pedidos>
    <pedido codigo="Z2345627"  observaciones="urgente" plazo_revision="3" >
        
        <trabajador nombre="Jose Luis"/>
       <fecha dia="12" mes="12" anio="1987"/>
        <observaciones >hola</observaciones>
        <articulo cod_articulo="32">
           <n_unidades >3</n_unidades>
           <precio>66</precio>
           <observaciones>s d</observaciones>
        </articulo>

    </pedido>
</pedidos>
