=== javierbarbe/ordenadornegro/XML/practica xml dtd xmlschema/practica3m.dtd
<!ELEMENT pedidos (pedido+)>
<!ELEMENT pedido  (trabajador,fecha,observaciones?,articulo,sucursal,albaran)>
    <!ATTLIST pedido codigo  ID #REQUIRED >
 
    <!ATTLIST pedido plazo_revision CDATA #REQUIRED>
    <!ELEMENT trabajador EMPTY>
       <!ATTLIST trabajador nombre CDATA #REQUIRED>
    <!ELEMENT fecha EMPTY> 
        <!ATTLIST fecha dia CDATA  #REQUIRED>
        <!ATTLIST fecha mes CDATA  #REQUIRED>
        <!ATTLIST fecha anio CDATA  #REQUIRED>
    <!ELEMENT observaciones (#PCDATA)>
        <!ATTLIST observaciones tipo (urgente|incompleto) #IMPLIED>
    <!ELEMENT articulo (n_unidades,precio,observaciones)>
        <!ELEMENT n_unidades (#PCDATA)>
        <!ELEMENT precio (#PCDATA)>
        <!ATTLIST articulo cod_articulo CDATA  #REQUIRED>
    <!ELEMENT sucursal (direccion,direccion_envio+)>
        <!ELEMENT direccion (#PCDATA)>
        <!ELEMENT direccion_envio (#PCDATA)>
    <!ELEMENT albaran (#PCDATA)>

=== javierbarbe/ordenadornegro/XML/practica xml dtd xmlschema/practicadtd3m.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE pedidos SYSTEM "./practica3m.dtd">
<pedidos>
    <pedido codigo="Z2345627"   plazo_revision="3" >
      
       <trabajador nombre="Jose Luis"/>
       <fecha dia="12" mes="12" anio="1987"/>
       <observaciones tipo="urgente"></observaciones>
        <articulo cod_articulo="32">
           <n_unidades >3</n_unidades>
           <precio>66</precio>
           <observaciones>s d</observaciones>
        </articulo>
        <sucursal>
                <direccion> mi casa
                </direccion>
                <direccion_envio> dire envio 1

                </direccion_envio>
                <direccion_envio>
                dire envio 1
                </direccion_envio>
            </sucursal>
            <albaran>1233</albaran>

    </pedido>
    <pedido codigo="Z2345622"   plazo_revision="3" >
      
       <trabajador nombre="Jose Luis"/>
       <fecha dia="12" mes="12" anio="1987"/>
       <observaciones tipo="urgente"></observaciones>
        <articulo cod_articulo="32">
           <n_unidades >3</n_unidades>
           <precio>66</precio>
           <observaciones>s d</observaciones>
        </articulo>
        <sucursal>
                <direccion> mi casa
                </direccion>
                <direccion_envio> Envio 1

                </direccion_envio>
                <direccion_envio>
              dire envio 2
                </direccion_envio>
            </sucursal>
            <albaran>1233</albaran>

    </pedido>
</pedidos>
