=== javierbarbe/ordenadornegro/XML/practica xml dtd xmlschema/practica3m.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="pedidos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pedido" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="trabajador">
                                <xs:complexType>
                                    <xs:attribute name="nombre" type="palabra" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="fecha">
                                <xs:complexType>
                                    <xs:attribute name="dia" type="day"/>
                                    <xs:attribute name="mes" type="month"/>
                                    <xs:attribute name="anio" type="year"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="observaciones" minOccurs="0">
                                <xs:complexType mixed="true">
                                    <xs:attribute name="tipo" type="tipoObserva" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="articulo">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="n_unidades" type="xs:positiveInteger"/>
                                        <xs:element name="precio" type="xs:positiveInteger"/>
                                        <xs:element name="observaciones" type="palabra"/>
                                    </xs:sequence>
                                    <xs:attribute name="cod_articulo" type="codigo3cifras"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="sucursal">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="direccion" type="xs:string"/>
                                        <xs:element name="direccion_envio" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="albaran" type="xs:string" />
                        </xs:sequence>
                        <xs:attribute name="codigo" type="codigoLetra" use="required" />
                        <xs:attribute name="observaciones">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="(urgente| incompleto)"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="plazo_revision" type="plazo"/>
                        
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="codigoLetra">
        <xs:restriction base="xs:token">
            <xs:pattern value="[A-Z]\d{7}"/>
            
        </xs:restriction>
    
        
     
    </xs:simpleType>

    <xs:simpleType name="palabra">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z\s]*"/>
        </xs:restriction>
    </xs:simpleType>

<xs:simpleType name="tipoObserva">
    <xs:restriction base="xs:string">
        <xs:pattern value="urgente|incompleto"/>
    </xs:restriction>
</xs:simpleType>

  <xs:simpleType name="plazo">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d+-\d+\sdias"/>
        </xs:restriction>
    </xs:simpleType>

     <xs:simpleType name="codigo3cifras">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{3}-\d{3}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="day">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="31"/>

        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="month">
        <xs:restriction base="xs:integer">
           <xs:minInclusive value="1"/>
           <xs:maxInclusive value="12"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="year">
        <xs:restriction base="xs:integer">
            <xs:pattern value="19[6-9]\d|200[0-2]"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== javierbarbe/ordenadornegro/XML/practica xml dtd xmlschema/practica3m.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<pedidos  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="./practica3m.xsd">



    <pedido codigo="Z2345627"  observaciones="urgente" plazo_revision="3-4 dias" >
        
        <trabajador nombre="Jose Luis"/>
       <fecha dia="12" mes="12" anio="1987"/>
        <observaciones tipo="urgente"> Ha ocurrido uin problema </observaciones>
        <articulo cod_articulo="AAA-222">
           <n_unidades >3</n_unidades>
           <precio>66</precio>
           <observaciones>sd</observaciones>
        </articulo>
        <sucursal>
                <direccion> mi casa
                </direccion>
                <direccion_envio> direccion envio 1

                </direccion_envio>
                <direccion_envio>
                direccion envio 2
                </direccion_envio>
            </sucursal>
            <albaran>1233</albaran>

    </pedido>
    <pedido codigo="Z2345632"  observaciones="urgente" plazo_revision="3-4 dias" >
        
            <trabajador nombre="Jose Luis"/>
           <fecha dia="12" mes="12" anio="1987"/>
           
            <articulo cod_articulo="AAH-222">
               <n_unidades >3</n_unidades>
               <precio>66</precio>
               <observaciones></observaciones>
            </articulo>
            <sucursal>
                <direccion> origen
                                </direccion>
                <direccion_envio> direccion envio 1

                </direccion_envio>
                <direccion_envio>
                    envio 2
                </direccion_envio>
            </sucursal>
            <albaran>1233</albaran>



        </pedido>
</pedidos>
