=== javierbarbe/ordenadornegro/XML/ejerciciosClase/agenda.dtd
<!ELEMENT agenda(persona)*>
<!ELEMENT persona(nombre,apellido,direccion,telefonos)>
<!ELEMENT telefonos(fijo ?,movil +,trabajo *)> <!-- permite tener uno o mas de un movil, o mas de un telefono de trabajo, fijo 0 alguno-->
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT fijo (#PCDATA)>
<!ELEMENT movil (#PCDATA)>
<!ELEMENT trabajo (#PCDATA)>

=== javierbarbe/ordenadornegro/XML/ejerciciosClase/ejemplo1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE agenda SYSTEM "agenda.dtd">
<agenda>
        <persona>
                    <nombre>Perico</nombre>
                    <apellido> El de los Palotes</apellido>
                    <direccion>C/el empecinado</direccion>
                    <telefonos> 
                            <fijo>91 856 35 14</fijo>
                            <movil>657 123 845</movil>
                            <trabajo>98 745 12 32</trabajo>
                    </telefonos>
       </persona> 
</agenda>
