=== javierbarbe/ordenadornegro/XML/cursoAprendeXML/futbol.dtd
<!ELEMENT club (ligas)>
<!ELEMENT ligas (nivel, resto)>
    <!ELEMENT nivel (liga*)>
        <!ELEMENT liga ( equipo+)>
            <!ELEMENT equipo (entrenador*, jugador+)>
                <!ELEMENT entrenador (edad?, peinado?)>
                    <!ELEMENT edad (#PCDATA)>
                    <!ELEMENT peinado (#PCDATA)>
                <!ELEMENT jugador (dorsal,posicion,edad)>
                    <!ELEMENT dorsal (#PCDATA)>
                    <!ELEMENT posicion (#PCDATA)>
                    <!-- <!ELEMENT edad (#PCDATA)> -->
        <!ATTLIST liga nombre CDATA #REQUIRED>
        <!ATTLIST equipo nombre CDATA #REQUIRED>
        <!ATTLIST entrenador nombre CDATA #REQUIRED>
        <!ATTLIST jugador nombre CDATA  "CR7" >
    <!ELEMENT resto   EMPTY>

=== javierbarbe/ordenadornegro/XML/cursoAprendeXML/equiposfutbol.xml
<?xml version = "1.0" encoding = "UTF-8"  standalone ="no"?>
<!DOCTYPE club SYSTEM "./futbol.dtd">
<club>
<ligas>
    <nivel>
        <liga nombre="española">
            <equipo nombre="real Madrid">
                <entrenador nombre="zizu">
                    <edad> 48</edad>
                    <peinado>   rasurado</peinado>
                </entrenador>
                <jugador nombre="">
                    <dorsal> 13 </dorsal>
                    <posicion> delantero </posicion>
                    <edad> 22 </edad>
                </jugador>
            </equipo>
        </liga>
        <liga nombre="italiana">
            <equipo nombre="juventus">
            <entrenador nombre="del Piero">
            </entrenador>
                <jugador nombre="">
                    <dorsal> 7 </dorsal>
                    <posicion> extremo </posicion>
                    <edad> 33 </edad>
                </jugador>
            </equipo>
        </liga>
    </nivel>
    <resto></resto>

</ligas>
</club>
